package springcamp2017.session.asyncmonitoring.gunlee.threadlocal.in;

/**
 * @author Gun Lee (gunlee01@gmail.com) on 2017. 4. 17.
 */


    public class LambdaEx1 {
        void doIt(int idx) { Runnable r = () -> System.out.println(idx);}

        //private static synthetic lambda$doIt$0(I)V
//        private static void lambda$doIt$0(int paramIdx) {
//            System.out.println(paramIdx);
//        }

        //On bootstrapping (LambdaMetafactory)
        //Generated by ASM library and vm innerclass loaded by anonymous classloader
//        static class LambdaEx1$$Lambda$1 implements Runnable {
//            private final int arg$1;
//            private LambdaEx1$$Lambda$1(int arg$1) {
//                this.arg$1 = arg$1;
//            }
//
//            private static Runnable get$Lambda(int arg$1) {
//                return new LambdaEx1$$Lambda$1(arg$1);
//            }
//
//            @Override public void run() {
//                lambda$doIt$0(arg$1);
//            }
//        }




    public static void main(String[] args) {
        new LambdaEx1().doIt(100);
    }
//    void test() {
//        LambdaEx1$$Lambda$1 x = new LambdaEx1$$Lambda$1(100);
//    }
}
